version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - sport
      - sportsman

  sport:
    build:
      context: ./Sport
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  sportsman:
    build:
      context: ./Sportsman
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

