### Get all sports
GET http://localhost:8083/sports
Accept: application/json

### Get a specific sport by ID
GET http://localhost:8083/sports/123e4567-e89b-12d3-a456-426614174000
Accept: application/json

### Create a new sport
POST http://localhost:8083/sports
Content-Type: application/json

{
  "name": "American Football"
}

### Update an existing sport
PUT http://localhost:8083/sports/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Soccer"
}

### Delete a sport by ID
DELETE http://localhost:8083/sports/123e4567-e89b-12d3-a456-426614174000

### Get all sportsmen
GET http://localhost:8083/sportsmen
Accept: application/json

### Get all sportsmen in a specific sport
GET http://localhost:8083/sportsmen/123e4567-e89b-12d3-a456-426614174000
Accept: application/json

### Add a sportsman to a specific sport
POST http://localhost:8083/sportsmen/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Pele",
  "rating": 95,
  "sportName": "Soccer"
}

### Delete a specific sportsman
DELETE http://localhost:8082/sportsmen/{id}
