logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200, http://localhost:4200/**"  # Allow Angular app
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            max-age: 3600
      routes:
        - id: sport-service
          uri: http://localhost:8081
          predicates:
            - Path=/sports/**
        - id: sportsmen-service
          uri: http://localhost:8082
          predicates:
            - Path=/sportsmen/**
  application:
    name: gateway-service

server:
  port: 8083 # Port for the Gateway Service