spring:
  main:
    web-application-type: reactive  # Enable reactive web stack (needed for Spring Cloud Gateway)
  cloud:
    gateway:
      routes:
        - id: sport-service
          uri: http://localhost:8081
          predicates:
            - Path=/sports/**
        - id: sportsmen-service
          uri: http://localhost:8082
          predicates:
            - Path=/sportsmen/**
  application:
    name: gateway-service

server:
  port: 8083 # Port for the Gateway Service